id: I141DE557
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:22:13+00:00'
last_modified: '2022-06-08T11:13:42.022150+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30539
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམར་ཁྲིད་ཐམས་ཅད་མཁྱེན་པར་བགྲོད་པའི་བདེ་ལམ་གྱི་ཟིན་བྲིས་ཡབ་རྗེ་བླ་མའི་ཞལ་གྱི་བདུད་རྩི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F662:
      image_group_id: I6457
      title: ''
      total_pages: 416
      order: 1
      base_file: F662.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
