id: P009464
initial_creation_type: ocr
source_metadata:
  id: bdr:W30539
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམར་ཁྲིད་ཐམས་ཅད་མཁྱེན་པར་བགྲོད་པའི་བདེ་ལམ་གྱི་ཟིན་བྲིས་ཡབ་རྗེ་བླ་མའི་ཞལ་གྱི་བདུད་རྩི
  author: ''
  volumes: {}
